### ISSUE TITLE
Duper doesn't find mods with improperly named PERSONALITIES.json files on Linux

### ISSUE THREAD

**Issue by P33ry** [Barleytree/Dupery#9]
# Issue
Tried to run _Dupery_ and _Print Cassidy_ with the _ONI Linux/SteamOS version_ without success.

While both mods are recognized by the ingame mod menu and mentioned in _Player.log_, Dupery does not recognize the _Print Cassidy_ mod and therefore also no Cassidy is added to the Duplicant pool. 

I assume this to be the issue by the difference in _Player.log_ under the _ONI_ Linux version and the Windows version. Also I've confirmed this setup to work under Windows.

# Setup
 - ONI Linux version (_ONI_ Build: U46-552078-V, taken from the main menu)
 - _Arch Linux 6.2.10-arch1-1_ (just to mention a version, doubt it matters)
 - _ONI_ without any DLCs (doubt that matters)
 - _Dupery_ (installed via Steam workshop)
 - _Print Cassidy_ (installed via Steam workshop)
 - activate both mods in the main menu, restart the game and ensure they stay checked
 - no other mods or specific saves involved

# Steps to reproduce
 - install _Dupery_ via Steam workshop
 - install _Print Cassidy_ via Steam workshop
 - Start _ONI_ and create a new game
 - Observe _Player.log_ for the list of added Personalities by _Dupery_ and note _Cassidy_ is missing. (Alternative: try re-rolling endlessly to find Cassidy)

# What I've tried
My overall goal has been to learn how to and create a custom duplicant (in terms of appearance) myself. For this I've used _Print Cassidy_ to test the workflow before actually doing any own edits.

As I was figuring things out I've tried several other approaches to see what works and what doesn't.
## Edit _PERSONALITIES.json_ in the Dupery mod folder
(Path: `/home/myuser/.config/unity3d/Klei/Oxygen Not Included/mods/Steam/2679326313/PERSONALITIES.json`)

According to your [instruction manual](https://github.com/Barleytree/Dupery/wiki/Mod-Instruction-Manual) I've added Dracula with only vanilla appearances. Which **works** without issues.

I've also tried to get it to use `"hair_cassidy"` as taken from the neat reference photo. This did not work although the duplicant appeared in the list but used a vanilla hair style instead. Hair style Nr. 1 I think.

## Using Windows instead
Using the same setup as described above I've tried to get Cassidy with ONI windows which worked without any hassle.

# Logs
[Player.log (Linux)](https://github.com/Barleytree/Dupery/files/11239361/Player.log)

# Side Note
Following your manual I've tried deleting any of the JSON files to reset Dupery as well as completely deleting & reinstalling the files via Steam workshop at several points without result.

I've not confirmed if multiple people have the same issue. 

Feel free to leave this issue unresolved if it's too much effort.

**Comment by Yaksinikos** [comment]
Can be fixed easily:
All Mod Makers have to be aware of, that Linux is case-sensitive, as soon as you rename personalities.json to PERSONALITIES.json - all those mods work.

**Comment by P33ry** [comment]
> Can be fixed easily: All Mod Makers have to be aware of, that Linux is case-sensitive, as soon as you rename personalities.json to PERSONALITIES.json - all those mods work.

Good catch.
I did get the cassidy mod to work after renaming the file to the expected name _PERSONALITIES.json_.

Since this is more an issue with those mods than Dupery ideally it should also be fixed there. 
Although it might be easier for everyone if Dupery could handle this instead of every mod making changes (which some probably won't). Should be simple.

I'll look into making a PR. Gotta figure out the build process of this first though.
